/**
 * In-place .pptx editing via direct OOXML manipulation (jszip).
 *
 * pptxgenjs is write-only — it cannot open an existing deck — so before this
 * module the only "edit" was regenerating the whole file, which loses every
 * image/chart/theme on untouched slides. Editing the slide XML inside the
 * zip preserves all of that: only the text runs (and, for delete, the
 * slide's registration entries) change.
 *
 * Scope is deliberately text-level: replace text runs, retitle a slide,
 * delete a slide. Layout/image/chart changes still go through regeneration
 * (presentation_create) — structural OOXML surgery (relationship wiring,
 * content-type overrides for NEW parts) is where corrupt decks come from.
 */
import JSZip from "jszip";

const SLIDE_RE = /^ppt\/slides\/slide(\d+)\.xml$/;

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function unescapeXml(s: string): string {
  return s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Slide part names in deck order (slide1.xml, slide2.xml, ...). */
export function slideFileNames(zip: JSZip): string[] {
  return Object.keys(zip.files)
    .filter((f) => SLIDE_RE.test(f))
    .sort((a, b) => Number(a.match(SLIDE_RE)![1]) - Number(b.match(SLIDE_RE)![1]));
}

/** Plain text of one slide: the concatenated <a:t> runs, entity-decoded. */
export function slideText(xml: string): string {
  return [...xml.matchAll(/<a:t>([^<]*)<\/a:t>/g)].map((m) => unescapeXml(m[1])).join(" ");
}

export interface ReplaceResult { replacements: number; slidesTouched: number[] }

/**
 * Find/replace inside text runs only — markup is never touched, so a `find`
 * that happens to match a tag name can't corrupt the deck. `slide` (1-based)
 * scopes to one slide; omitted = whole deck. Matching is case-sensitive
 * exact substring, applied per run (text split across runs by PowerPoint's
 * spell-check/formatting boundaries won't match — report 0 and let the
 * caller try a shorter fragment).
 */
export async function replaceTextInDeck(
  zip: JSZip,
  find: string,
  replace: string,
  slide?: number,
): Promise<ReplaceResult> {
  const files = slideFileNames(zip);
  const targets = slide ? [files[slide - 1]].filter(Boolean) : files;
  if (slide && targets.length === 0) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  const findRe = new RegExp(escapeRegExp(find), "g");
  let replacements = 0;
  const slidesTouched: number[] = [];
  for (const f of targets) {
    const xml = await zip.file(f)!.async("string");
    let hits = 0;
    // Match against the DECODED run text (so find:"A & B" works against a
    // run stored as "A &amp; B"), then re-encode the whole updated run.
    const next = xml.replace(/<a:t>([^<]*)<\/a:t>/g, (run, raw: string) => {
      const decoded = unescapeXml(raw);
      const updated = decoded.replace(findRe, () => { hits++; return replace; });
      return updated === decoded ? run : `<a:t>${escapeXml(updated)}</a:t>`;
    });
    if (hits > 0) {
      zip.file(f, next);
      replacements += hits;
      slidesTouched.push(Number(f.match(SLIDE_RE)![1]));
    }
  }
  return { replacements, slidesTouched };
}

/**
 * Replace the title text of one slide (1-based). Targets the first text run
 * inside the title/ctrTitle placeholder shape; falls back to the slide's
 * first run when no placeholder is marked (decks generated by tools often
 * skip ph types).
 */
export async function setSlideTitle(zip: JSZip, slide: number, title: string): Promise<void> {
  const files = slideFileNames(zip);
  const f = files[slide - 1];
  if (!f) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  const xml = await zip.file(f)!.async("string");
  const escaped = escapeXml(title);

  // Title placeholder shape: <p:ph type="title"/> or "ctrTitle" inside <p:sp>.
  const phMatch = xml.match(/<p:sp>(?:(?!<\/p:sp>)[\s\S])*?type="(?:title|ctrTitle)"(?:(?!<\/p:sp>)[\s\S])*?<\/p:sp>/);
  if (phMatch) {
    const shape = phMatch[0];
    if (/<a:t>[^<]*<\/a:t>/.test(shape)) {
      let first = true;
      const newShape = shape.replace(/<a:t>[^<]*<\/a:t>/g, (run) => {
        if (!first) return run;
        first = false;
        return `<a:t>${escaped}</a:t>`;
      });
      zip.file(f, xml.replace(shape, newShape));
      return;
    }
  }
  if (!/<a:t>[^<]*<\/a:t>/.test(xml)) throw new Error(`Slide ${slide} has no text runs to retitle`);
  let first = true;
  zip.file(f, xml.replace(/<a:t>[^<]*<\/a:t>/g, (run) => {
    if (!first) return run;
    first = false;
    return `<a:t>${escaped}</a:t>`;
  }));
}

/**
 * Delete one slide (1-based): drop the part + its rels, deregister it from
 * presentation.xml's sldIdLst (via the rId that points at it), its
 * relationship entry, and the [Content_Types] override. Remaining parts are
 * NOT renumbered — PowerPoint resolves slides through the relationship
 * graph, not file names, so gaps are valid (and renumbering would mean
 * rewriting every cross-part reference, the risky surgery this module
 * avoids).
 */
export async function deleteSlide(zip: JSZip, slide: number): Promise<void> {
  const files = slideFileNames(zip);
  const f = files[slide - 1];
  if (!f) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  if (files.length === 1) throw new Error("Refusing to delete the only slide — a deck needs at least one");

  const relsPath = "ppt/_rels/presentation.xml.rels";
  const relsXml = await zip.file(relsPath)!.async("string");
  const target = f.replace(/^ppt\//, "");
  const relMatch = relsXml.match(
    new RegExp(`<Relationship[^>]*Id="([^"]+)"[^>]*Target="${escapeRegExp(target)}"[^>]*/>|<Relationship[^>]*Target="${escapeRegExp(target)}"[^>]*Id="([^"]+)"[^>]*/>`),
  );
  if (!relMatch) throw new Error(`Could not find relationship entry for ${target} — deck structure not recognized`);
  const rId = relMatch[1] ?? relMatch[2];

  const presPath = "ppt/presentation.xml";
  const presXml = await zip.file(presPath)!.async("string");
  const sldIdRe = new RegExp(`<p:sldId[^>]*r:id="${escapeRegExp(rId)}"[^>]*/>`);
  if (!sldIdRe.test(presXml)) throw new Error(`Could not find sldId entry for ${rId} in presentation.xml`);

  zip.file(presPath, presXml.replace(sldIdRe, ""));
  zip.file(relsPath, relsXml.replace(relMatch[0], ""));
  const ctPath = "[Content_Types].xml";
  const ctXml = await zip.file(ctPath)!.async("string");
  zip.file(ctPath, ctXml.replace(new RegExp(`<Override[^>]*PartName="/${escapeRegExp(f)}"[^>]*/>`), ""));
  zip.remove(f);
  const slideRels = f.replace("ppt/slides/", "ppt/slides/_rels/") + ".rels";
  if (zip.file(slideRels)) zip.remove(slideRels);
}
