import { describe, it, expect, beforeAll } from "vitest";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import JSZip from "jszip";
import { replaceTextInDeck, setSlideTitle, deleteSlide, addImageSlide, slideFileNames, slideText } from "./pptx-edit.js";

// 1×1 transparent PNG — enough for structural assertions.
const PNG_1x1 = Buffer.from(
  "89504E470D0A1A0A0000000D4948445200000001000000010806000000" +
  "1F15C4890000000A49444154789C63000100000500010D0A2DB40000000049454E44AE426082",
  "hex",
);

// Real .pptx fixture generated by the same library the create tools use —
// the roundtrip (generate → edit zip → re-read) is the whole point: these
// edits must survive PowerPoint's actual OOXML shapes, not synthetic XML.
let deckPath: string;

async function makeDeck(): Promise<string> {
  const mod = await import("pptxgenjs");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const Ctor = (mod as any).default ?? mod;
  const pptx = new Ctor();
  const dir = mkdtempSync(join(tmpdir(), "pptx-edit-"));
  const fp = join(dir, "deck.pptx");
  const s1 = pptx.addSlide();
  s1.addText("Quarterly Review Q3", { x: 0.5, y: 0.5, w: 9, h: 1, placeholder: "title" });
  s1.addText("Revenue grew in Q3", { x: 0.5, y: 2, w: 9, h: 1 });
  const s2 = pptx.addSlide();
  s2.addText("Q3 Highlights", { x: 0.5, y: 0.5, w: 9, h: 1 });
  const s3 = pptx.addSlide();
  s3.addText("Obsolete slide", { x: 0.5, y: 0.5, w: 9, h: 1 });
  await pptx.writeFile({ fileName: fp });
  return fp;
}

async function loadDeck(fp: string): Promise<JSZip> {
  return JSZip.loadAsync(readFileSync(fp));
}

async function allText(zip: JSZip): Promise<string[]> {
  const out: string[] = [];
  for (const f of slideFileNames(zip)) out.push(slideText(await zip.file(f)!.async("string")));
  return out;
}

beforeAll(async () => { deckPath = await makeDeck(); });

describe("pptx-edit roundtrip on a pptxgenjs-generated deck", () => {
  it("replace_text across the whole deck", async () => {
    const zip = await loadDeck(deckPath);
    const r = await replaceTextInDeck(zip, "Q3", "Q4");
    expect(r.replacements).toBeGreaterThanOrEqual(3);
    const texts = await allText(zip);
    expect(texts.join(" ")).toContain("Q4");
    expect(texts.join(" ")).not.toContain("Q3");
  });

  it("replace_text scoped to one slide leaves others untouched", async () => {
    const zip = await loadDeck(deckPath);
    const r = await replaceTextInDeck(zip, "Q3", "Q4", 1);
    expect(r.slidesTouched).toEqual([1]);
    const texts = await allText(zip);
    expect(texts[0]).toContain("Q4");
    expect(texts[1]).toContain("Q3");
  });

  it("replace_text escapes XML-special replacement text", async () => {
    const zip = await loadDeck(deckPath);
    await replaceTextInDeck(zip, "Highlights", "Wins & <Losses>");
    const xml = await zip.file(slideFileNames(zip)[1])!.async("string");
    expect(xml).toContain("Wins &amp; &lt;Losses&gt;");
    // Still a parseable run — no raw < injected into markup.
    expect(slideText(xml)).toContain("Wins & <Losses>");
  });

  it("returns 0 replacements (not a throw) when text isn't found", async () => {
    const zip = await loadDeck(deckPath);
    const r = await replaceTextInDeck(zip, "no-such-string", "x");
    expect(r.replacements).toBe(0);
  });

  it("set_title rewrites slide 1's title run", async () => {
    const zip = await loadDeck(deckPath);
    await setSlideTitle(zip, 1, "FY26 Kickoff");
    const texts = await allText(zip);
    expect(texts[0]).toContain("FY26 Kickoff");
    expect(texts[0]).toContain("Revenue grew");
  });

  it("delete_slide removes the part and deregisters it", async () => {
    const zip = await loadDeck(deckPath);
    await deleteSlide(zip, 3);
    expect(slideFileNames(zip)).toHaveLength(2);
    const pres = await zip.file("ppt/presentation.xml")!.async("string");
    const rels = await zip.file("ppt/_rels/presentation.xml.rels")!.async("string");
    expect(rels).not.toContain("slides/slide3.xml");
    expect((pres.match(/<p:sldId /g) ?? []).length).toBe(2);
    const texts = await allText(zip);
    expect(texts.join(" ")).not.toContain("Obsolete");
  });

  it("refuses to delete the only slide and out-of-range slides", async () => {
    const zip = await loadDeck(deckPath);
    await expect(deleteSlide(zip, 9)).rejects.toThrow(/does not exist/);
    await deleteSlide(zip, 3);
    await deleteSlide(zip, 2);
    await expect(deleteSlide(zip, 1)).rejects.toThrow(/only slide/);
  });

  it("edited deck survives a zip rebuild and re-read", async () => {
    const zip = await loadDeck(deckPath);
    await replaceTextInDeck(zip, "Quarterly Review", "Annual Review");
    await deleteSlide(zip, 3);
    const rebuilt = await JSZip.loadAsync(await zip.generateAsync({ type: "nodebuffer" }));
    const texts = await allText(rebuilt);
    expect(texts).toHaveLength(2);
    expect(texts[0]).toContain("Annual Review");
  });

  it("add_image_slide appends a fully-registered image slide", async () => {
    const zip = await loadDeck(deckPath);
    const pos = await addImageSlide(zip, {
      buffer: PNG_1x1, mimeType: "image/png", width: 800, height: 600,
      title: "Site Photos", caption: "The new office",
    });
    expect(pos).toBe(4);

    const rebuilt = await JSZip.loadAsync(await zip.generateAsync({ type: "nodebuffer" }));
    expect(slideFileNames(rebuilt)).toHaveLength(4);
    // All five registrations present.
    const ct = await rebuilt.file("[Content_Types].xml")!.async("string");
    expect(ct).toContain('PartName="/ppt/slides/slide4.xml"');
    expect(ct).toMatch(/Extension="png"/);
    const rels = await rebuilt.file("ppt/_rels/presentation.xml.rels")!.async("string");
    expect(rels).toContain("slides/slide4.xml");
    const pres = await rebuilt.file("ppt/presentation.xml")!.async("string");
    expect((pres.match(/<p:sldId /g) ?? []).length).toBe(4);
    const slideRels = await rebuilt.file("ppt/slides/_rels/slide4.xml.rels")!.async("string");
    expect(slideRels).toContain("slideLayout");
    expect(slideRels).toContain("../media/");
    expect(rebuilt.file("ppt/media/image_lax_4.png")).toBeTruthy();
    // Title + caption render as text runs; the image is referenced by the slide.
    const slideXml = await rebuilt.file("ppt/slides/slide4.xml")!.async("string");
    expect(slideText(slideXml)).toContain("Site Photos");
    expect(slideText(slideXml)).toContain("The new office");
    expect(slideXml).toContain('r:embed="rId2"');
  });

  it("add_image_slide numbers past gaps left by delete_slide", async () => {
    const zip = await loadDeck(deckPath);
    await deleteSlide(zip, 2);
    const pos = await addImageSlide(zip, { buffer: PNG_1x1, mimeType: "image/png", width: 100, height: 100 });
    // slide3 still exists, so the new part must be slide4 — not a collision.
    expect(zip.file("ppt/slides/slide4.xml")).toBeTruthy();
    expect(pos).toBe(3); // 1-based position in the remaining deck order
  });
});
