/**
 * In-place .pptx editing via direct OOXML manipulation (jszip).
 *
 * pptxgenjs is write-only — it cannot open an existing deck — so before this
 * module the only "edit" was regenerating the whole file, which loses every
 * image/chart/theme on untouched slides. Editing the slide XML inside the
 * zip preserves all of that: only the text runs (and, for delete, the
 * slide's registration entries) change.
 *
 * Scope: replace text runs, retitle a slide, delete a slide, and APPEND an
 * image slide (the one structural op users actually ask for — "add photos
 * to my deck" — and the inverse of deleteSlide's registration surgery:
 * mint the part + media + rels + content-type + sldId instead of removing
 * them). Other layout/chart changes still go through regeneration
 * (presentation_create) — free-form OOXML surgery is where corrupt decks
 * come from.
 */
import JSZip from "jszip";

const SLIDE_RE = /^ppt\/slides\/slide(\d+)\.xml$/;

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function unescapeXml(s: string): string {
  return s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Slide part names in deck order (slide1.xml, slide2.xml, ...). */
export function slideFileNames(zip: JSZip): string[] {
  return Object.keys(zip.files)
    .filter((f) => SLIDE_RE.test(f))
    .sort((a, b) => Number(a.match(SLIDE_RE)![1]) - Number(b.match(SLIDE_RE)![1]));
}

/** Plain text of one slide: the concatenated <a:t> runs, entity-decoded. */
export function slideText(xml: string): string {
  return [...xml.matchAll(/<a:t>([^<]*)<\/a:t>/g)].map((m) => unescapeXml(m[1])).join(" ");
}

export interface ReplaceResult { replacements: number; slidesTouched: number[] }

/**
 * Find/replace inside text runs only — markup is never touched, so a `find`
 * that happens to match a tag name can't corrupt the deck. `slide` (1-based)
 * scopes to one slide; omitted = whole deck. Matching is case-sensitive
 * exact substring, applied per run (text split across runs by PowerPoint's
 * spell-check/formatting boundaries won't match — report 0 and let the
 * caller try a shorter fragment).
 */
export async function replaceTextInDeck(
  zip: JSZip,
  find: string,
  replace: string,
  slide?: number,
): Promise<ReplaceResult> {
  const files = slideFileNames(zip);
  const targets = slide ? [files[slide - 1]].filter(Boolean) : files;
  if (slide && targets.length === 0) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  const findRe = new RegExp(escapeRegExp(find), "g");
  let replacements = 0;
  const slidesTouched: number[] = [];
  for (const f of targets) {
    const xml = await zip.file(f)!.async("string");
    let hits = 0;
    // Match against the DECODED run text (so find:"A & B" works against a
    // run stored as "A &amp; B"), then re-encode the whole updated run.
    const next = xml.replace(/<a:t>([^<]*)<\/a:t>/g, (run, raw: string) => {
      const decoded = unescapeXml(raw);
      const updated = decoded.replace(findRe, () => { hits++; return replace; });
      return updated === decoded ? run : `<a:t>${escapeXml(updated)}</a:t>`;
    });
    if (hits > 0) {
      zip.file(f, next);
      replacements += hits;
      slidesTouched.push(Number(f.match(SLIDE_RE)![1]));
    }
  }
  return { replacements, slidesTouched };
}

/**
 * Replace the title text of one slide (1-based). Targets the first text run
 * inside the title/ctrTitle placeholder shape; falls back to the slide's
 * first run when no placeholder is marked (decks generated by tools often
 * skip ph types).
 */
export async function setSlideTitle(zip: JSZip, slide: number, title: string): Promise<void> {
  const files = slideFileNames(zip);
  const f = files[slide - 1];
  if (!f) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  const xml = await zip.file(f)!.async("string");
  const escaped = escapeXml(title);

  // Title placeholder shape: <p:ph type="title"/> or "ctrTitle" inside <p:sp>.
  const phMatch = xml.match(/<p:sp>(?:(?!<\/p:sp>)[\s\S])*?type="(?:title|ctrTitle)"(?:(?!<\/p:sp>)[\s\S])*?<\/p:sp>/);
  if (phMatch) {
    const shape = phMatch[0];
    if (/<a:t>[^<]*<\/a:t>/.test(shape)) {
      let first = true;
      const newShape = shape.replace(/<a:t>[^<]*<\/a:t>/g, (run) => {
        if (!first) return run;
        first = false;
        return `<a:t>${escaped}</a:t>`;
      });
      zip.file(f, xml.replace(shape, newShape));
      return;
    }
  }
  if (!/<a:t>[^<]*<\/a:t>/.test(xml)) throw new Error(`Slide ${slide} has no text runs to retitle`);
  let first = true;
  zip.file(f, xml.replace(/<a:t>[^<]*<\/a:t>/g, (run) => {
    if (!first) return run;
    first = false;
    return `<a:t>${escaped}</a:t>`;
  }));
}

/**
 * Delete one slide (1-based): drop the part + its rels, deregister it from
 * presentation.xml's sldIdLst (via the rId that points at it), its
 * relationship entry, and the [Content_Types] override. Remaining parts are
 * NOT renumbered — PowerPoint resolves slides through the relationship
 * graph, not file names, so gaps are valid (and renumbering would mean
 * rewriting every cross-part reference, the risky surgery this module
 * avoids).
 */
export async function deleteSlide(zip: JSZip, slide: number): Promise<void> {
  const files = slideFileNames(zip);
  const f = files[slide - 1];
  if (!f) throw new Error(`Slide ${slide} does not exist (deck has ${files.length})`);
  if (files.length === 1) throw new Error("Refusing to delete the only slide — a deck needs at least one");

  const relsPath = "ppt/_rels/presentation.xml.rels";
  const relsXml = await zip.file(relsPath)!.async("string");
  const target = f.replace(/^ppt\//, "");
  const relMatch = relsXml.match(
    new RegExp(`<Relationship[^>]*Id="([^"]+)"[^>]*Target="${escapeRegExp(target)}"[^>]*/>|<Relationship[^>]*Target="${escapeRegExp(target)}"[^>]*Id="([^"]+)"[^>]*/>`),
  );
  if (!relMatch) throw new Error(`Could not find relationship entry for ${target} — deck structure not recognized`);
  const rId = relMatch[1] ?? relMatch[2];

  const presPath = "ppt/presentation.xml";
  const presXml = await zip.file(presPath)!.async("string");
  const sldIdRe = new RegExp(`<p:sldId[^>]*r:id="${escapeRegExp(rId)}"[^>]*/>`);
  if (!sldIdRe.test(presXml)) throw new Error(`Could not find sldId entry for ${rId} in presentation.xml`);

  zip.file(presPath, presXml.replace(sldIdRe, ""));
  zip.file(relsPath, relsXml.replace(relMatch[0], ""));
  const ctPath = "[Content_Types].xml";
  const ctXml = await zip.file(ctPath)!.async("string");
  zip.file(ctPath, ctXml.replace(new RegExp(`<Override[^>]*PartName="/${escapeRegExp(f)}"[^>]*/>`), ""));
  zip.remove(f);
  const slideRels = f.replace("ppt/slides/", "ppt/slides/_rels/") + ".rels";
  if (zip.file(slideRels)) zip.remove(slideRels);
}

// ── Append an image slide ──────────────────────────────────────────────────

const EMU_PER_PX = 9525; // 96 dpi
const SLIDE_NS =
  'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' +
  'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" ' +
  'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"';

export interface ImageSlideInput {
  buffer: Buffer;
  /** Only formats PowerPoint renders everywhere. */
  mimeType: "image/png" | "image/jpeg" | "image/gif";
  width: number;
  height: number;
  title?: string;
  caption?: string;
  alt?: string;
}

/** Slide canvas size in EMU from presentation.xml (sldSz). */
async function slideSize(zip: JSZip): Promise<{ cx: number; cy: number }> {
  const presXml = await zip.file("ppt/presentation.xml")!.async("string");
  const m = presXml.match(/<p:sldSz[^>]*\bcx="(\d+)"[^>]*\bcy="(\d+)"/);
  if (!m) throw new Error("presentation.xml has no sldSz — deck structure not recognized");
  return { cx: Number(m[1]), cy: Number(m[2]) };
}

/**
 * Append a new slide containing one centered image (plus optional title and
 * caption). All five registrations a slide needs are minted here — part,
 * media, slide rels (layout borrowed from the last existing slide), the
 * [Content_Types] entries, and the presentation.xml.rels + sldIdLst pair.
 * Returns the new slide's 1-based position.
 */
export async function addImageSlide(zip: JSZip, img: ImageSlideInput): Promise<number> {
  const files = slideFileNames(zip);
  if (files.length === 0) throw new Error("Deck has no slides — not a .pptx?");
  const nextNum = Math.max(...files.map((f) => Number(f.match(SLIDE_RE)![1]))) + 1;
  const slidePath = `ppt/slides/slide${nextNum}.xml`;

  // Media part + content-type default for its extension.
  const ext = img.mimeType === "image/png" ? "png" : img.mimeType === "image/jpeg" ? "jpeg" : "gif";
  const mediaPath = `ppt/media/image_lax_${nextNum}.${ext}`;
  zip.file(mediaPath, img.buffer);
  const ctPath = "[Content_Types].xml";
  let ctXml = await zip.file(ctPath)!.async("string");
  if (!new RegExp(`<Default[^>]*Extension="${ext}"`, "i").test(ctXml)) {
    ctXml = ctXml.replace("</Types>", `<Default Extension="${ext}" ContentType="${img.mimeType}"/></Types>`);
  }
  ctXml = ctXml.replace(
    "</Types>",
    `<Override PartName="/${slidePath}" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>`,
  );
  zip.file(ctPath, ctXml);

  // Borrow the last slide's layout relationship so the new slide inherits a
  // valid master chain instead of minting a layout from scratch.
  const lastRelsPath = files[files.length - 1].replace("ppt/slides/", "ppt/slides/_rels/") + ".rels";
  const lastRels = await zip.file(lastRelsPath)?.async("string");
  const layoutTarget = lastRels?.match(/<Relationship[^>]*Type="[^"]*\/slideLayout"[^>]*Target="([^"]+)"/)?.[1]
    ?? lastRels?.match(/Target="([^"]*slideLayouts[^"]+)"/)?.[1];
  if (!layoutTarget) throw new Error(`Could not find a slideLayout relationship on ${lastRelsPath} — deck structure not recognized`);

  // Geometry: image centered in the lower ~85% (room for the title band),
  // fit preserving aspect ratio, sized from pixel dims at 96dpi.
  const { cx, cy } = await slideSize(zip);
  const hasTitle = !!img.title?.trim();
  const boxTop = hasTitle ? Math.round(cy * 0.18) : Math.round(cy * 0.06);
  const boxH = cy - boxTop - Math.round(cy * 0.08);
  const boxW = Math.round(cx * 0.88);
  const ratio = img.width > 0 && img.height > 0 ? img.width / img.height : 4 / 3;
  let w = Math.min(boxW, Math.round(img.width * EMU_PER_PX));
  let h = Math.round(w / ratio);
  if (h > boxH) { h = boxH; w = Math.round(h * ratio); }
  const x = Math.round((cx - w) / 2);
  const y = boxTop + Math.round((boxH - h) / 2);

  const titleSp = hasTitle
    ? `<p:sp><p:nvSpPr><p:cNvPr id="3" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>` +
      `<p:spPr><a:xfrm><a:off x="${Math.round(cx * 0.06)}" y="${Math.round(cy * 0.05)}"/><a:ext cx="${Math.round(cx * 0.88)}" cy="${Math.round(cy * 0.1)}"/></a:xfrm>` +
      `<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>` +
      `<p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="2800" b="1"/><a:t>${escapeXml(img.title!.trim())}</a:t></a:r></a:p></p:txBody></p:sp>`
    : "";
  const captionSp = img.caption?.trim()
    ? `<p:sp><p:nvSpPr><p:cNvPr id="4" name="Caption"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>` +
      `<p:spPr><a:xfrm><a:off x="${Math.round(cx * 0.06)}" y="${cy - Math.round(cy * 0.07)}"/><a:ext cx="${Math.round(cx * 0.88)}" cy="${Math.round(cy * 0.06)}"/></a:xfrm>` +
      `<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>` +
      `<p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="1400" i="1"/><a:t>${escapeXml(img.caption.trim())}</a:t></a:r></a:p></p:txBody></p:sp>`
    : "";

  zip.file(
    slidePath,
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<p:sld ${SLIDE_NS}><p:cSld><p:spTree>` +
    `<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>` +
    `<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>` +
    titleSp +
    `<p:pic><p:nvPicPr><p:cNvPr id="2" name="Picture" descr="${escapeXml(img.alt ?? img.caption ?? img.title ?? "Image")}"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr>` +
    `<p:blipFill><a:blip r:embed="rId2"/><a:stretch><a:fillRect/></a:stretch></p:blipFill>` +
    `<p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${w}" cy="${h}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>` +
    captionSp +
    `</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`,
  );

  // Slide rels: layout (rId1) + the image (rId2).
  zip.file(
    `ppt/slides/_rels/slide${nextNum}.xml.rels`,
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="${layoutTarget}"/>` +
    `<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image_lax_${nextNum}.${ext}"/>` +
    `</Relationships>`,
  );

  // Register in presentation.xml.rels + sldIdLst (append = last position).
  const relsPath = "ppt/_rels/presentation.xml.rels";
  const relsXml = await zip.file(relsPath)!.async("string");
  const maxRid = Math.max(0, ...[...relsXml.matchAll(/Id="rId(\d+)"/g)].map((m) => Number(m[1])));
  const newRid = `rId${maxRid + 1}`;
  zip.file(relsPath, relsXml.replace(
    "</Relationships>",
    `<Relationship Id="${newRid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${nextNum}.xml"/></Relationships>`,
  ));

  const presPath = "ppt/presentation.xml";
  const presXml = await zip.file(presPath)!.async("string");
  const maxSldId = Math.max(255, ...[...presXml.matchAll(/<p:sldId[^>]*\bid="(\d+)"/g)].map((m) => Number(m[1])));
  if (!presXml.includes("</p:sldIdLst>")) throw new Error("presentation.xml has no sldIdLst — deck structure not recognized");
  zip.file(presPath, presXml.replace(
    "</p:sldIdLst>",
    `<p:sldId id="${maxSldId + 1}" r:id="${newRid}"/></p:sldIdLst>`,
  ));

  return slideFileNames(zip).length;
}
