// This desktop's STABLE cryptographic identity for agentxos — an ed25519 keypair
// generated once and persisted in ~/.lax. The PUBLIC key is registered with agentxos
// (POST /api/devices/register) as this machine's device identity; the PRIVATE key NEVER
// leaves the machine (constitution §6 / architecture Auth model). The keypair is the
// stable identity (survives logout); the server-assigned deviceId + session token live
// separately in storage.ts (they clear on logout, the keypair does not).
//
// Today the broker authenticates connects with the session TOKEN (device-code), not a
// per-device signature, so the private key isn't exercised yet — but registering a real
// public key (not a throwaway string) means a future signed-per-device-token upgrade
// needs no re-pairing. File perms are 0600 (private key at rest).

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { generateKeyPairSync } from "node:crypto";
import { getLaxDir } from "../../lax-data-dir.js";
import { atomicWriteFileSync } from "../../server-utils.js";

export interface DeviceIdentity {
  /** ed25519 public key (SPKI PEM) — registered with agentxos as this device's identity. */
  publicKey: string;
  /** ed25519 private key (PKCS8 PEM) — NEVER leaves this machine (constitution §6). */
  privateKey: string;
}

function identityPath(): string {
  return join(getLaxDir(), "agentxos-identity.json");
}

/** Load the persisted identity, or null if absent/corrupt (regenerated by the caller). */
export function loadDeviceIdentity(): DeviceIdentity | null {
  const path = identityPath();
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8")) as Partial<DeviceIdentity>;
    if (typeof parsed.publicKey === "string" && typeof parsed.privateKey === "string") {
      return { publicKey: parsed.publicKey, privateKey: parsed.privateKey };
    }
  } catch {
    /* corrupt → regenerate */
  }
  return null;
}

/** Return this machine's agentxos identity, generating + persisting an ed25519 keypair
 *  on first call. Stable across restarts and logouts so re-registration is idempotent. */
export function getOrCreateDeviceIdentity(): DeviceIdentity {
  const existing = loadDeviceIdentity();
  if (existing) return existing;

  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const identity: DeviceIdentity = {
    publicKey: publicKey.export({ format: "pem", type: "spki" }).toString(),
    privateKey: privateKey.export({ format: "pem", type: "pkcs8" }).toString(),
  };
  atomicWriteFileSync(identityPath(), JSON.stringify(identity, null, 2), { mode: 0o600 });
  return identity;
}
