// `read` on a .pptx or .docx returns the document's text instead of the
// binary refusal. The deck is generated by the same library the create tools
// use, so the extraction is proven against real OOXML, slide by slide, with
// speaker notes resolved through the slide's rels.
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import JSZip from "jszip";
import { extractOfficeText, isOfficeTextFile } from "./office-text.js";

let deckPath: string;

beforeAll(async () => {
  const mod = await import("pptxgenjs");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const Ctor = (mod as any).default ?? mod;
  const pptx = new Ctor();
  const dir = mkdtempSync(join(tmpdir(), "office-text-"));
  deckPath = join(dir, "deck.pptx");
  const s1 = pptx.addSlide();
  s1.addText("Quarterly Review Q3", { x: 0.5, y: 0.5, w: 9, h: 1 });
  s1.addText("Revenue grew in Q3", { x: 0.5, y: 2, w: 9, h: 1 });
  s1.addNotes("Pause here for questions.");
  const s2 = pptx.addSlide();
  s2.addText("Q3 Highlights", { x: 0.5, y: 0.5, w: 9, h: 1 });
  await pptx.writeFile({ fileName: deckPath });
});

describe("isOfficeTextFile", () => {
  it("needs both the extension and the zip magic", async () => {
    const bytes = readFileSync(deckPath);
    expect(isOfficeTextFile(deckPath, bytes)).toBe(true);
    expect(isOfficeTextFile(deckPath.replace(/\.pptx$/, ".zip"), bytes)).toBe(false);
    expect(isOfficeTextFile(deckPath, Buffer.from("not a zip at all"))).toBe(false);
  });
});

describe("extractOfficeText", () => {
  it("a deck comes back slide by slide, one line per paragraph, with its speaker notes", async () => {
    const text = await extractOfficeText(deckPath, readFileSync(deckPath));
    expect(text).toContain("[PowerPoint deck — 2 slide(s), text extracted]");
    const slide1 = text.indexOf("--- Slide 1 ---");
    const slide2 = text.indexOf("--- Slide 2 ---");
    expect(slide1).toBeGreaterThan(0);
    expect(slide2).toBeGreaterThan(slide1);
    const first = text.slice(slide1, slide2);
    expect(first).toContain("Quarterly Review Q3\nRevenue grew in Q3");
    expect(first).toContain("Speaker notes:\nPause here for questions.");
    expect(text.slice(slide2)).toContain("Q3 Highlights");
    expect(text.slice(slide2)).not.toContain("Speaker notes");
  });

  it("a slide without text says so rather than vanishing from the numbering", async () => {
    const zip = await JSZip.loadAsync(readFileSync(deckPath));
    const blank = (await zip.file("ppt/slides/slide2.xml")!.async("string")).replace(/<a:t>[^<]*<\/a:t>/g, "<a:t></a:t>");
    zip.file("ppt/slides/slide2.xml", blank);
    const fp = join(mkdtempSync(join(tmpdir(), "office-text-")), "blank.pptx");
    writeFileSync(fp, await zip.generateAsync({ type: "nodebuffer" }));
    const text = await extractOfficeText(fp, readFileSync(fp));
    expect(text).toContain("--- Slide 2 ---\n(no text)");
  });

  it("a corrupt container is an error, not a crash", async () => {
    await expect(extractOfficeText("x.pptx", Buffer.from("PK\u0003\u0004 garbage"))).rejects.toThrow();
  });
});
