import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spreadsheetTools } from "./spreadsheet-tools.js";
import { documentTools } from "./document-tools.js";
import { pdfTools } from "./pdf-tools.js";
import { presentationTools } from "./presentation-tools.js";
import { SOURCES_DOC_SENTENCE, SOURCES_PARAM_SCHEMA } from "./shared/provenance-sources.js";
import { TOOL_POLICIES_APPS } from "../tool-policy/tool-policies.apps.js";
import type { ToolDefinition } from "../types.js";

/**
 * The `sources` provenance claim on the deliverable writer families.
 *
 * Three invariants pinned here:
 *  1. Every writer action's doc carries THE sentence, byte-exact (the wording
 *     is grep-enforceable on purpose — one phrasing across the whole surface),
 *     and every collapsed family schema + writer inner schema declares the
 *     optional `sources` array.
 *  2. `sources` is a CLAIM, not path input: it never appears in the families'
 *     pathArgs declarations (it must not gate or widen file access) and is
 *     never required.
 *  3. Passing `sources` changes NOTHING about the write: the artifact bytes
 *     and the tool result are identical with and without it (Date frozen so
 *     embedded timestamps can't mask a real divergence).
 */

// Byte-exact wording — deliberately duplicated from the constant so a rewrite
// of either side fails here.
const SENTENCE =
  "If the data came from a URL or file, pass sources:[{url, ref}] — it is recorded for verification.";

const FAMILIES: { tools: ToolDefinition[]; name: string; writers: string[]; nonWriters: string[] }[] = [
  { tools: spreadsheetTools, name: "spreadsheet", writers: ["write", "edit"], nonWriters: ["read", "query"] },
  { tools: documentTools, name: "document", writers: ["create", "template"], nonWriters: ["read", "edit"] },
  { tools: pdfTools, name: "pdf", writers: ["create", "merge"], nonWriters: ["read", "extract_tables"] },
  { tools: presentationTools, name: "presentation", writers: ["create", "from_outline"], nonWriters: ["add_slide", "edit"] },
];

const family = (tools: ToolDefinition[], name: string): ToolDefinition => {
  const t = tools.find((x) => x.name === name);
  if (!t) throw new Error(`tool ${name} not found`);
  return t;
};

const count = (haystack: string, needle: string): number => haystack.split(needle).length - 1;

/** The `• action(sig)` doc line generated by collapseFamily for one action. */
const signatureOf = (desc: string, action: string): string => {
  const m = desc.match(new RegExp(`• ${action}\\(([^)]*)\\)`));
  if (!m) throw new Error(`no per-action doc line for ${action}`);
  return m[1];
};

describe("sources — schema and description surface", () => {
  it("the doc sentence constant is byte-exact", () => {
    expect(SOURCES_DOC_SENTENCE).toBe(SENTENCE);
  });

  it.each(FAMILIES)("$name: exactly the writer actions carry the sentence and the sources? param", ({ tools, name, writers, nonWriters }) => {
    const t = family(tools, name);
    // One sentence per writer action doc, and none anywhere else.
    expect(count(t.description, SENTENCE)).toBe(writers.length);
    const props = (t.parameters as { properties: Record<string, unknown>; required?: string[] }).properties;
    expect(props.sources).toBe(SOURCES_PARAM_SCHEMA);
    for (const a of writers) expect(signatureOf(t.description, a)).toContain("sources?");
    for (const a of nonWriters) expect(signatureOf(t.description, a)).not.toContain("sources");
  });

  it("sources entries are the 4 optional strings mirroring ProvenanceSource — none required", () => {
    expect(Object.keys(SOURCES_PARAM_SCHEMA.items.properties)).toEqual(["url", "file", "ref", "note"]);
    expect((SOURCES_PARAM_SCHEMA.items as { required?: string[] }).required).toBeUndefined();
    expect(SOURCES_PARAM_SCHEMA.type).toBe("array");
  });

  it.each(FAMILIES)("$name: sources is a claim — never a pathArg, never required", ({ tools, name }) => {
    const policy = TOOL_POLICIES_APPS[name];
    expect(policy).toBeDefined();
    for (const pa of policy.pathArgs ?? []) expect(pa.arg).not.toBe("sources");
    const required = (family(tools, name).parameters as { required?: string[] }).required ?? [];
    expect(required).not.toContain("sources");
  });
});

describe("sources — passing it changes nothing about the write", () => {
  const dir = mkdtempSync(join(tmpdir(), "sources-claim-"));
  const SOURCES = [
    { url: "https://example.com/q3-report", ref: "rows 2-40" },
    { file: "notes/q3.md", ref: "cell B5", note: "headline figure" },
  ];

  beforeAll(() => {
    // Freeze ONLY Date: xlsx/pdf artifacts embed creation timestamps, which
    // would differ between the two writes and mask (or fake) a divergence.
    vi.useFakeTimers({ now: new Date("2026-01-02T03:04:05.678Z"), toFake: ["Date"] });
  });
  afterAll(() => {
    vi.useRealTimers();
    rmSync(dir, { recursive: true, force: true });
  });

  const sha = (fp: string): string => createHash("sha256").update(readFileSync(fp)).digest("hex");

  it("spreadsheet write: byte-identical artifact and result, with and without sources", async () => {
    const spreadsheet = family(spreadsheetTools, "spreadsheet");
    const data = JSON.stringify([{ Product: "Widget", Price: 9.99 }, { Product: "Gadget", Price: 24.99 }]);
    const plain = join(dir, "plain.xlsx");
    const claim = join(dir, "claim.xlsx");
    const a = await spreadsheet.execute({ action: "write", file_path: plain, data });
    const b = await spreadsheet.execute({ action: "write", file_path: claim, data, sources: SOURCES });
    expect(a.isError).toBeFalsy();
    expect(b.isError).toBeFalsy();
    expect(sha(claim)).toBe(sha(plain));
    expect(String(b.content).replaceAll(claim, plain)).toBe(String(a.content));
  });

  it("pdf create: byte-identical artifact and result, with and without sources", async () => {
    const pdf = family(pdfTools, "pdf");
    const content = "# Q3\n\nRevenue grew 15% YoY.\n\n- Widget\n- Gadget";
    const plain = join(dir, "plain.pdf");
    const claim = join(dir, "claim.pdf");
    const a = await pdf.execute({ action: "create", file_path: plain, content });
    const b = await pdf.execute({ action: "create", file_path: claim, content, sources: SOURCES });
    expect(a.isError).toBeFalsy();
    expect(b.isError).toBeFalsy();
    expect(sha(claim)).toBe(sha(plain));
    expect(String(b.content).replaceAll(claim, plain)).toBe(String(a.content));
  });

  it("document create: accepts sources and the write still lands", async () => {
    const document = family(documentTools, "document");
    const fp = join(dir, "claim.docx");
    const r = await document.execute({ action: "create", file_path: fp, content: "# Report\n\nBody.", sources: SOURCES });
    expect(r.isError).toBeFalsy();
    expect(readFileSync(fp).length).toBeGreaterThan(0);
  });
});
